--- #YAML:1.0
name: Class-CompoundMethods
version: 0.03
author:
  - "Joshua ben Jore" <jjore@cpan.org>
abstract: Create methods from components
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
